# Generated by Django 5.2.6 on 2025-09-22 21:56

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_time', models.TimeField(default='05:30')),
                ('closing_time', models.TimeField(default='23:59')),
                ('price_per_slot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='stadiums.field')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='stadiums.stadium'),
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stadiums/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadiums.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposit_held', 'Deposit Held'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('maintenance', 'Maintenance')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stadiums.field')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['timeslot'], name='stadiums_bo_timeslo_1a4c96_gist')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'deposit_held', 'confirmed'])), expressions=[(models.F('field'), '='), (models.F('timeslot'), '&&')], name='exclude_overlapping_bookings')],
            },
        ),
    ]
