# Generated by Django 5.2.6 on 2025-09-22 22:31

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_bookings',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deposit_held', 'Deposit Held'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['confirmed', 'deposit_held'])), expressions=[(models.F('field'), '='), (models.F('timeslot'), '&&')], name='exclude_overlapping_confirmed_bookings'),
        ),
    ]
