# Generated by Django 5.2.6 on 2025-09-23 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_booking_address_booking_age_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='field',
            name='opening_time',
            field=models.TimeField(default=datetime.time(5, 30)),
        ),
    ]
