# Generated by Django 5.2.6 on 2025-09-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_match_goals_team_a_alter_match_goals_team_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
    ]
