# Generated by Django 5.2.6 on 2025-09-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_rename_date_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
