# Generated by Django 5.2.6 on 2025-09-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_match_match_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_date',
            new_name='date',
        ),
    ]
