# Generated by Django 5.2.6 on 2025-11-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_group_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/', verbose_name='شعار الدوري'),
        ),
    ]
