# Generated by Django 5.2.6 on 2025-12-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_league_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط شعار الدوري'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط شعار الفريق'),
        ),
    ]
