# Generated by Django 5.2.6 on 2025-12-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_alter_league_logo_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(choices=[(32, 'دور الـ 32'), (16, 'دور الـ 16'), (8, 'ربع النهائي'), (4, 'نصف النهائي'), (2, 'النهائي'), (1, 'البطل')])),
                ('match_order', models.IntegerField()),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_matches', to='leagues.league')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='leagues.knockoutmatch')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ko_home_matches', to='leagues.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ko_away_matches', to='leagues.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ko_wins', to='leagues.team')),
            ],
        ),
    ]
