# Generated by Django 5.2.6 on 2025-12-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_knockoutmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutmatch',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المكان'),
        ),
        migrations.AddField(
            model_name='knockoutmatch',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='الوقت'),
        ),
    ]
